default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['COMUNES_DATABASE_HOST'] %>
  username: <%= ENV['COMUNES_DATABASE_USER'] %>
  password: <%= ENV['COMUNES_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: comunes_api_development

test:
  <<: *default
  database: comunes_api_test

production:
  <<: *default
  database: comunes_api_production